language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
    - $HOME/.npm

install:
  - npm install --no-optionals

stages:
  - name: test
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: test
      script: npm run compile && npm run lint && npm test
    - stage: deploy
      deploy:
        skip_cleanup: true
        provider: npm
        email: tech@maas.global
        api_key: $NPM_TOKEN
      after_deploy: ./scripts/tag.sh
